appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: oiolBSC+boN7r/sMx8DfyWUmxebA32ovQ5Ht329CKn3S9M+O2FK4fBob0cyGOmPiupOtu1XzNQ/EFzdUD6CIaMEJ4ol1MI6DsO8pf2Cx3YDl2EY3aSL5MRB5bIkAeJxTqSPRJSogqPnTmGZLgkk6jFQOuN80tpjNvbHTN6EPz/MIFL1gld23kfwNTOmv/eEujR//tqQmhZE3O14tWcSbgEaWUHDhRNC7lU8N8+he8LAVyo0h4RCSymtd9fHCCYKtE2MQ9wK8QQJK87X6+7Hb4iGn/2rFFUVmUqEpKpbdxypPFjyU/0mNuQIlMJQrxizsnAt9NWZs9vkC8y1GfL9/LfIeeBDNyddnf9LPhhVObFJ/EGAnraKm1G6xc/8pFEUEuCY7eRw0snlM1KKDOkFH9gqgQyYO0fzhpU4PvGzBHOlTgJir4iudGg89Sf3KSnh+NDS5Wq68J2D0qSW5+zW9ZuwH+96vOe57OmJMZPXCJ1aVU7bGF8ymP78YZlwaHlNRiEZKUfCm06SlEASN9ynBPbkpFweLiOvDYIoEEsRQsqEIFzGcR/PBMZKvWFQCEFoKcfwHbdpc4nOMKgMsb1N7VvafmUBsX9NlhyKKOmBtpPXhvubKey7/N8GmRVhUiRkZSVqzCkznYl+Y5VnVE2waOEDXU6YB6+nwknUiDqwzUAk=
conda_forge_output_validation: true
